"""program_synthesis_agent_v2.py — self-contained ARC-AGI-3 agent (v2.0)

Generated by 4CBOn2_Kaggle2.ipynb (Arena, Agent Mode) — M1 build, 2026-09-29.
Contract: class MyAgent with choose_action(frames, latest_frame) and
is_done(frames, latest_frame). numpy + stdlib only; no network; no UL code;
never hangs (every decide path is wrapped, with a cheapest-legal-action
fallback).

DESIGN DIRECTIVE (provenance — concepts that shaped components; the builder
regenerates this header from build_manifest.json in M3):
  - DreamCoder (program-synthesis datasets)   -> hypothesis bank as a program library
  - HARC / Karel (program induction)          -> action->effect programs, not pixel policies
  - CLEVR (object-centric perception)         -> connected components + attribute binding
  - MiniGrid / Procgen (grid world-models)    -> probe-learned control maps, goal seeking
  - ARC-AGI-3-Agents traces (arcprize)        -> RESET discipline, per-game available_actions
  - CoT-Hub (reasoning traces)                -> structured reasoning blob per action
  - App knowledge DB: "world models+planning" -> DSL frame prediction before acting
  - App knowledge DB: "memory and retrieval"  -> ledger vs projections vs working state
  - Universal Learner spec (R1,R4-R12,R16,R17)-> governance set: append-only ledger,
     verifier independence, evidence classes VERIFIED/CORROBORATED, stale-not-deleted,
     quarantine, detection cue + recovery, no silent override, no scalar scores

v2.0 features (locked scope):
  F1 frame diffing + no-op blacklist   F2 cross-level verified replay
  F3 level-1-first exploration
"""
import copy
import time
from collections import deque

import numpy as np

# ============================================================================
# SECTION 1 — PROTOCOL LAYER (official arcengine when available, else a
# byte-compatible shim; carried over from v1, proven on Kaggle/Colab/local)
# ============================================================================
GRID = 64   # official ARC-AGI-3 screen size (ACTION6 x,y range 0..63)
CELL = 8    # logical lattice pitch used by perception helpers

try:
    from arcengine import FrameData as _RealFrameData  # noqa: F401
    from arcengine import GameAction, GameState
    from arcengine.enums import (SimpleAction, ComplexAction, FrameData,
                                 FrameDataRaw, ActionInput)  # noqa: F401
    ARCENGINE_AVAILABLE = True
except Exception:
    ARCENGINE_AVAILABLE = False

    from enum import Enum

    class GameState(str, Enum):
        NOT_PLAYED = "NOT_PLAYED"
        NOT_FINISHED = "NOT_FINISHED"
        WIN = "WIN"
        GAME_OVER = "GAME_OVER"

    class SimpleAction:
        def __init__(self, game_id: str = ""):
            self.game_id = game_id

        def model_dump(self):
            return {"game_id": self.game_id}

    class ComplexAction:
        def __init__(self, game_id: str = "", x: int = 0, y: int = 0):
            if not (0 <= x <= 63 and 0 <= y <= 63):
                raise ValueError("x and y must be within [0, 63]")
            self.game_id = game_id
            self.x = x
            self.y = y

        def model_dump(self):
            return {"game_id": self.game_id, "x": self.x, "y": self.y}

    class GameAction(Enum):
        RESET = (0, SimpleAction)
        ACTION1 = (1, SimpleAction)
        ACTION2 = (2, SimpleAction)
        ACTION3 = (3, SimpleAction)
        ACTION4 = (4, SimpleAction)
        ACTION5 = (5, SimpleAction)
        ACTION6 = (6, ComplexAction)
        ACTION7 = (7, SimpleAction)

        def __init__(self, action_id, action_type):
            self._value_ = action_id
            self._atype = action_type
            self.action_data = action_type()

        def is_simple(self):
            return self._atype is SimpleAction

        def is_complex(self):
            return self._atype is ComplexAction

        def set_data(self, data):
            self.action_data = self._atype(**data)
            return self.action_data

        @classmethod
        def from_id(cls, action_id):
            for a in cls:
                if a.value == action_id:
                    return a
            raise ValueError(f"No GameAction with id {action_id}")

    class ActionInput:  # noqa: D401
        def __init__(self, id=GameAction.RESET, data=None, reasoning=None):
            self.id = id
            self.data = data or {}
            self.reasoning = reasoning

    class FrameData:
        def __init__(self, game_id="", frame=None, state=GameState.NOT_PLAYED,
                     levels_completed=0, win_levels=0, action_input=None,
                     guid=None, full_reset=False, available_actions=None):
            self.game_id = game_id
            self.frame = frame or []
            self.state = state
            self.levels_completed = levels_completed
            self.win_levels = win_levels
            self.action_input = action_input or ActionInput()
            self.guid = guid
            self.full_reset = full_reset
            self.available_actions = list(available_actions or [])

        def is_empty(self):
            return len(self.frame) == 0


def _state_name(state):
    """Robust state comparison across real/shim/serialized harnesses."""
    try:
        return str(getattr(state, "value", state)).split(".")[-1]
    except Exception:
        return ""


def _grid_of(frame):
    """Best-effort grid extraction; None when no usable frame data."""
    try:
        layers = getattr(frame, "frame", None)
        if not layers:
            layers = getattr(frame, "_frame", None)
        if not layers:
            return None
        arr = np.asarray(layers[0])
        if arr.ndim != 2:
            return None
        return arr.astype(np.int64, copy=False)
    except Exception:
        return None


def merged_view(frame):
    """All layers overlaid: later layers win where nonzero (v1 helper)."""
    try:
        layers = getattr(frame, "frame", None) or []
        if not layers:
            return None
        base = np.asarray(layers[0]).astype(np.int64, copy=False)
        for extra in layers[1:]:
            arr = np.asarray(extra)
            if arr.shape == base.shape:
                base = np.where(arr != 0, arr, base)
        return base
    except Exception:
        return None


# ============================================================================
# SECTION 2 — PERCEPTION (v1, carried over: connected components + salience)
# ============================================================================
def find_objects(grid):
    """Connected components of same-coloured, non-background pixels."""
    objects = []
    visited = set()
    h, w = grid.shape
    for r in range(h):
        for c in range(w):
            if grid[r, c] == 0 or (r, c) in visited:
                continue
            color = int(grid[r, c])
            obj_id = len(objects) + 1
            q = deque([(r, c)])
            visited.add((r, c))
            pixels = []
            min_r, max_r, min_c, max_c = r, r, c, c
            while q:
                cr, cc = q.popleft()
                pixels.append((cr, cc))
                min_r, max_r = min(min_r, cr), max(max_r, cr)
                min_c, max_c = min(min_c, cc), max(max_c, cc)
                for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                    nr, nc = cr + dr, cc + dc
                    if (0 <= nr < h and 0 <= nc < w and (nr, nc) not in visited
                            and grid[nr, nc] == color):
                        visited.add((nr, nc))
                        q.append((nr, nc))
            cy = sum(p[0] for p in pixels) / len(pixels)
            cx = sum(p[1] for p in pixels) / len(pixels)
            objects.append({"id": obj_id, "color": color,
                            "pixels": frozenset(pixels),
                            "bbox": (min_r, min_c, max_r, max_c),
                            "size": len(pixels), "centroid": (cy, cx)})
    return objects


def frame_diff(grid_a, grid_b):
    if grid_a is None or grid_b is None or grid_a.shape != grid_b.shape:
        return np.ones_like(np.asarray(grid_b), dtype=bool)
    return grid_a != grid_b


def salience_rank(objects):
    """Rarest colour first, then smallest (v1 ordering, kept for F3)."""
    color_count = {}
    for o in objects:
        color_count[o["color"]] = color_count.get(o["color"], 0) + 1
    ranked = sorted(objects,
                    key=lambda o: (color_count[o["color"]], o["size"], o["bbox"]))
    return ranked, color_count


# ============================================================================
# SECTION 3 — MICRO-DSL (only the prediction-relevant primitives)
# ============================================================================
def prim_recolor_region(grid, mask, new_color):
    g = copy.deepcopy(grid)
    g[mask] = new_color
    return g


def prim_move_region(grid, mask, dr, dc):
    g = copy.deepcopy(grid)
    color = int(g[mask][0]) if mask.any() else 0
    g[mask] = 0
    rows = np.nonzero(mask)[0] + dr
    cols = np.nonzero(mask)[1] + dc
    keep = ((rows >= 0) & (rows < g.shape[0])
            & (cols >= 0) & (cols < g.shape[1]))
    g[rows[keep], cols[keep]] = color
    return g


# ============================================================================
# SECTION 4 — GOVERNANCE (UL-derived): ledger, rule records, game knowledge
# ============================================================================
EFFECT_NO_EFFECT = "NO_EFFECT"
EFFECT_LOCAL = "LOCAL_CHANGE"
EFFECT_GLOBAL = "GLOBAL_CHANGE"
EFFECT_LEVEL = "LEVEL_ADVANCED"

EVIDENCE_VERIFIED = "VERIFIED"        # M-A analog: frame prediction validated
EVIDENCE_CORROBORATED = "CORROBORATED"  # M-B analog: consistent, unvalidated

STATUS_ACTIVE = "ACTIVE"
STATUS_STALE = "STALE"                # contradicted/superseded — surfaced, kept
STATUS_QUARANTINED = "QUARANTINED"    # exhausted — terminal for the episode

BLACKLIST_CAP = 64
SEQ_STORE_CAP = 60
GLOBAL_CHANGE_FRACTION = 0.25


class EpisodeLedger:
    """Append-only event log (UL R9). Everything else is a projection."""

    def __init__(self):
        self.events = []

    def append(self, kind, **payload):
        eid = len(self.events)
        self.events.append(dict(id=eid, kind=kind, **payload))
        return eid

    def __len__(self):
        return len(self.events)


class RuleRecord:
    """A learned rule with evidence class and status (UL R5/R6/R12 — no
    scalar scores, contradictions surface, quarantine is terminal)."""

    def __init__(self, rule_id, kind):
        self.rule_id = rule_id
        self.kind = kind
        self.evidence_class = None
        self.status = STATUS_ACTIVE
        self.success = 0
        self.fail = 0
        self.rotations = 0
        self.evidence = []  # ledger event ids

    def cite(self, eid):
        self.evidence.append(eid)


class GameKnowledge:
    """Cross-level / cross-episode knowledge for one game (projection)."""

    def __init__(self, game_id):
        self.game_id = game_id
        self.rules = {}     # selector name -> RuleRecord
        self.move = None    # {"dirs": {aid: (dr,dc)}, "player_color", "record"}
        self.sequences = {}  # level -> {"actions": [...], "evidence_class",
        #                       "aborts": int, "stale": bool}

    def rule(self, name):
        if name not in self.rules:
            self.rules[name] = RuleRecord(name, "click")
        return self.rules[name]

    def best_selector(self, order):
        """Level-1-first (F3): prefer rules that have succeeded, VERIFIED
        before CORROBORATED; never quarantined; stale goes last."""
        def key(sel):
            rec = self.rules.get(sel)
            if rec is None:
                return (2, 0, 0)          # untried: middle
            if rec.status == STATUS_QUARANTINED:
                return (9, 0, 0)
            if rec.status == STATUS_STALE:
                return (1, 0, 0)
            rank = {EVIDENCE_VERIFIED: 0, EVIDENCE_CORROBORATED: 1, None: 2}
            return (0, rank.get(rec.evidence_class, 2), -rec.success)
        return sorted(order, key=key)


def classify_effect(prev, cur, levels_before, levels_after):
    """F1: classify the observed effect of the last action."""
    if levels_after > levels_before:
        return EFFECT_LEVEL, 0
    d = frame_diff(prev, cur)
    n = int(d.sum())
    if n == 0:
        return EFFECT_NO_EFFECT, 0
    if n > GLOBAL_CHANGE_FRACTION * prev.size or n > 1024:
        return EFFECT_GLOBAL, n
    return EFFECT_LOCAL, n


# ============================================================================
# SECTION 5 — PROGRAM SYNTHESIS CORE v2
# ============================================================================
CLICK_SELECTORS = ["rarest_color", "smallest_object",
                   "corner_sample_color", "largest_object"]
PROBE_ATTEMPT_CAP = 3      # UL R8: cold start bounded by budget
REPLAY_ABORT_STALE = 2     # two aborts -> sequence STALE (surfaced, kept)


class ProgramSynthesisV2Core:
    """Framework-free decision core. Sees each frame exactly once via
    next_action(); all state changes are recorded in the ledger first."""

    GAME_MEMORY = {}   # game_id -> GameKnowledge (cross-episode projection)

    def __init__(self, verbose=False):
        self.verbose = verbose
        self._reset_episode()

    # ------------------------------------------------------------- lifecycle
    def _reset_episode(self):
        self.game_id = ""
        self.ledger = EpisodeLedger()
        self.history = []
        self.pending = None
        self.level = 0
        self.mode = None
        # click-game working state (per level)
        self.sel_order = list(CLICK_SELECTORS)
        self.queue = []
        self.queue_ptr = 0
        self.clicked_sig = set()
        self.blacklist = set()       # (level, action_id) for simple actions
        # move-game state
        self.dirs = {}
        self.probe_attempts = {}
        self.player_color = None
        self.stuck = 0
        # replay state (F2)
        self.replay = None
        # current level action sequence (ledger projection)
        self.level_actions = []
        self.level_verified = False

    def new_episode(self, game_id):
        know = ProgramSynthesisV2Core.GAME_MEMORY.get(game_id)
        self._reset_episode()
        self.game_id = game_id or ""
        if know is None:
            know = GameKnowledge(game_id)
            ProgramSynthesisV2Core.GAME_MEMORY[game_id] = know
        self.knowledge = know
        if know.move:
            self.dirs = dict(know.move.get("dirs") or {})
            self.player_color = know.move.get("player_color")
        self.sel_order = know.best_selector(list(CLICK_SELECTORS))
        self.ledger.append("EPISODE_START", game_id=self.game_id)

    # ------------------------------------------------------------- main entry
    def next_action(self, frame):
        """Returns (action_id, data, reasoning). One frame per call."""
        gid = ""
        try:
            gid = getattr(frame, "game_id", "") or ""
        except Exception:
            pass
        if gid and gid != self.game_id:
            self.new_episode(gid)

        grid = self._grid(frame)
        if grid is None:
            return 0, {"game_id": self.game_id}, {"note": "no frame data"}

        if self.history:
            try:
                self._process_feedback(self.history[-1], grid, frame)
            except Exception:
                self.pending = None  # degrade; diff copes on the next call
        self.history.append(grid)

        state = _state_name(getattr(frame, "state", None))
        if state in ("NOT_PLAYED", "GAME_OVER"):
            self._clear_level_state()
            self.ledger.append("RESET_ISSUED", why=state)
            return 0, {"game_id": self.game_id}, {
                "strategy": "reset", "why": state,
                "hypothesis": self.sel_order[0] if self.sel_order else None}

        avail = self._available(frame)
        if not avail:
            return 0, {"game_id": self.game_id}, {"note": "no available actions"}
        self.mode = "click" if 6 in avail else "move"

        # F2: replay a stored winning sequence for this level, if eligible
        if self.replay is None and self.mode:
            seqrec = self.knowledge.sequences.get(self.level)
            if seqrec and not seqrec.get("stale"):
                self.replay = {"actions": seqrec["actions"], "idx": 0}
                self.ledger.append("REPLAY_STARTED", level=self.level,
                                   evidence_class=seqrec["evidence_class"],
                                   n_actions=len(seqrec["actions"]))
                if self.verbose:
                    print(f"    [v2] replay level {self.level}: "
                          f"{len(seqrec['actions'])} actions "
                          f"({seqrec['evidence_class']})")
        if self.replay is not None:
            return self._replay_step(grid, frame, avail)

        if self.mode == "click":
            return self._click_policy(grid, frame, avail)
        return self._move_policy(grid, frame, avail)

    # ------------------------------------------------------------- feedback
    def _process_feedback(self, prev, cur, frame):
        levels_now = int(getattr(frame, "levels_completed", 0) or 0)
        effect, npx = classify_effect(prev, cur, self.level, levels_now)
        pend = self.pending or {}
        self.pending = None
        aid = pend.get("aid")
        verified = False
        self.ledger.append("EFFECT_CLASSIFIED", action=aid, effect=effect,
                           changed=npx, level=levels_now,
                           replay=bool(pend.get("replay")))

        # prediction validation (verifier independence: raw frames only)
        predicted = pend.get("predicted")
        if predicted is not None and effect in (EFFECT_LOCAL, EFFECT_GLOBAL):
            ok = float((predicted == cur).mean()) if predicted.shape == cur.shape else 0.0
            if ok >= 0.97:
                verified = True

        # record into the current level's action sequence (F2 storage)
        if aid is not None:
            self.level_actions.append({
                "aid": aid, "data": pend.get("data") or {},
                "effect": effect, "verified": verified})
            if verified:
                self.level_verified = True

        # replay verification (F2)
        if pend.get("replay"):
            expected = pend.get("expected")
            if effect != expected and effect != EFFECT_LEVEL:
                self._replay_abort(cause=f"expected {expected}, saw {effect}")
                return
            if effect == EFFECT_LEVEL:
                # the replayed sequence completed the level: fall through to
                # normal level-advance handling (stores/refreshes sequence,
                # updates level counters — no silent skip)
                self.replay = None
                self.ledger.append("REPLAY_STEP_DONE", effect=effect)
                self._on_level_advanced(levels_now, pend)
                return
            self.ledger.append("REPLAY_STEP_OK", effect=effect)
            return  # replay actions bypass rule bookkeeping

        # level advance (F2 storage point)
        if effect == EFFECT_LEVEL:
            self._on_level_advanced(levels_now, pend)
            return

        # rule feedback by pending kind
        kind = pend.get("kind")
        if effect == EFFECT_NO_EFFECT:
            self._on_no_effect(pend)
            if kind == "probe":
                # blocked probe: still counts its attempt (bounded cold start)
                self._learn_direction(prev, cur, aid)
        elif kind == "click":
            self._on_click_feedback(pend, effect, verified)
        elif kind == "probe":
            self._learn_direction(prev, cur, aid)
        elif kind == "move":
            self._on_move_feedback(pend, prev, cur, aid, verified)

    def _on_level_advanced(self, levels_now, pend):
        # store the winning sequence (skip stored no-effect exploration)
        seq = [a for a in self.level_actions if a["effect"] != EFFECT_NO_EFFECT]
        if 0 < len(self.level_actions) <= SEQ_STORE_CAP and seq:
            self.knowledge.sequences[self.level] = {
                "actions": seq,
                "evidence_class": (EVIDENCE_VERIFIED if self.level_verified
                                   else EVIDENCE_CORROBORATED),
                "aborts": 0, "stale": False}
            self.ledger.append("WIN_SEQUENCE_STORED", level=self.level,
                               n_actions=len(seq),
                               evidence_class=(
                                   EVIDENCE_VERIFIED if self.level_verified
                                   else EVIDENCE_CORROBORATED))
        # rule success
        rule_name = pend.get("rule")
        if self.mode == "move" and self.knowledge.move:
            rec = self.knowledge.move["record"]
            rec.success += 1
            rec.cite(self.ledger.append("RULE_SUCCESS", rule="move",
                                        level=levels_now))
            if rec.evidence_class is None:
                rec.evidence_class = EVIDENCE_CORROBORATED
        elif rule_name:
            rec = self.knowledge.rule(rule_name)
            rec.success += 1
            if rec.evidence_class is None:
                rec.evidence_class = EVIDENCE_CORROBORATED
                if self.verbose:
                    print(f"    [v2] CORROBORATED '{rule_name}' (level advanced)")
            rec.cite(self.ledger.append("RULE_SUCCESS", rule=rule_name,
                                        level=levels_now))
        self.ledger.append("LEVEL_ADVANCED", to=levels_now)
        self.level = levels_now
        self._clear_level_state()

    def _on_no_effect(self, pend):
        aid = pend.get("aid")
        kind = pend.get("kind")
        # F1 blacklist: clicks blacklist the target signature; simple actions
        # blacklist the action id for the level — but only in click-mode
        # games (in movement games a no-op can be positional, not useless).
        if kind == "click" and pend.get("sig"):
            self.clicked_sig.add(pend["sig"])
            if len(self.clicked_sig) > BLACKLIST_CAP:
                self.clicked_sig.pop()
        elif kind in ("simple", None) and self.mode != "move" and aid is not None:
            key = (self.level, aid)
            if key not in self.blacklist and len(self.blacklist) < BLACKLIST_CAP:
                self.blacklist.add(key)
                self.ledger.append("ACTION_BLACKLISTED", action=aid,
                                   level=self.level)
        if kind == "click" and pend.get("rule"):
            rec = self.knowledge.rule(pend["rule"])
            rec.fail += 1
        if kind == "move":
            self.stuck += 1

    def _on_click_feedback(self, pend, effect, verified):
        rule_name = pend.get("rule")
        if not rule_name:
            return
        rec = self.knowledge.rule(rule_name)
        if verified:
            rec.success += 1
            if rec.evidence_class != EVIDENCE_VERIFIED:
                rec.evidence_class = EVIDENCE_VERIFIED
                if self.verbose:
                    print(f"    [v2] VERIFIED '{rule_name}' (frame prediction "
                          f"matched)")
            rec.cite(self.ledger.append("RULE_VERIFIED", rule=rule_name))
        elif pend.get("predicted") is not None:
            # prediction mismatch — detection cue + recovery (UL R10),
            # no silent override (UL R12): a contradicted VERIFIED rule
            # goes STALE, surfaced, never quietly reused.
            rec.fail += 1
            if rec.evidence_class == EVIDENCE_VERIFIED:
                rec.status = STATUS_STALE
                self.ledger.append("RULE_STALE", rule=rule_name,
                                   cause="prediction mismatch after verification")
                if self.verbose:
                    print(f"    [v2] STALE '{rule_name}' (contradicted)")
            self._demote(rule_name, why="prediction mismatch")
        else:
            # GLOBAL change without a usable prediction: mild failure
            rec.fail += 1

    def _on_move_feedback(self, pend, prev, cur, aid, verified):
        if self.knowledge.move is None:
            return
        rec = self.knowledge.move["record"]
        if verified:
            rec.success += 1
            if rec.evidence_class != EVIDENCE_VERIFIED:
                rec.evidence_class = EVIDENCE_VERIFIED
                if self.verbose:
                    print("    [v2] VERIFIED move program (frame prediction "
                          "matched)")
            rec.cite(self.ledger.append("RULE_VERIFIED", rule="move"))
        self._learn_direction(prev, cur, aid)
        moved = bool(frame_diff(prev, cur).any())
        self.stuck = 0 if moved else self.stuck + 1

    def _learn_direction(self, prev, cur, aid):
        if aid is None or aid in self.dirs:
            return
        hole = (prev != 0) & (cur == 0)
        fill = (prev == 0) & (cur != 0)
        if hole.any() and fill.any():
            hr, hc = np.nonzero(hole)
            fr, fc = np.nonzero(fill)
            dr = int(round(fr.mean() - hr.mean()))
            dc = int(round(fc.mean() - hc.mean()))
            self.dirs[aid] = (int(np.sign(dr)) if abs(dr) > 1 else 0,
                              int(np.sign(dc)) if abs(dc) > 1 else 0)
            self.player_color = int(np.bincount(prev[hole]).argmax())
            if self.knowledge.move is None:
                self.knowledge.move = {
                    "dirs": {}, "player_color": None,
                    "record": RuleRecord("move", "control")}
            self.knowledge.move["dirs"] = dict(self.dirs)
            self.knowledge.move["player_color"] = self.player_color
        else:
            self.probe_attempts[aid] = self.probe_attempts.get(aid, 0) + 1
            if self.probe_attempts[aid] >= PROBE_ATTEMPT_CAP:
                self.dirs[aid] = (0, 0)   # give up on this action (quarantine)
                self.ledger.append("ACTION_QUARANTINED", action=aid,
                                   cause="no effect after "
                                         f"{PROBE_ATTEMPT_CAP} probes")

    # ------------------------------------------------------------- replay (F2)
    def _replay_step(self, grid, frame, avail):
        seq = self.replay["actions"]
        idx = self.replay["idx"]
        if idx >= len(seq):
            self.replay = None
            return self._click_policy(grid, frame, avail) \
                if self.mode == "click" else self._move_policy(grid, frame, avail)
        stored = seq[idx]
        aid, data = stored["aid"], dict(stored["data"])
        self.replay["idx"] = idx + 1
        self.pending = {
            "aid": aid, "data": data, "kind": "replay", "replay": True,
            "replay_idx": idx, "expected": stored["effect"], "predicted": None}
        reasoning = {"strategy": "verified_replay", "level": self.level,
                     "step": f"{idx + 1}/{len(seq)}",
                     "expected_effect": stored["effect"]}
        return aid, data, reasoning

    def _replay_abort(self, cause):
        seqrec = self.knowledge.sequences.get(self.level)
        if seqrec is not None:
            seqrec["aborts"] = seqrec.get("aborts", 0) + 1
            if seqrec["aborts"] >= REPLAY_ABORT_STALE:
                seqrec["stale"] = True
                self.ledger.append("SEQUENCE_STALE", level=self.level,
                                   cause=cause)
        self.ledger.append("REPLAY_ABORT", level=self.level, cause=cause)
        if self.verbose:
            print(f"    [v2] replay aborted ({cause}) -> exploration")
        self.replay = None

    # ------------------------------------------------------------- click games
    def _select_targets(self, sel, objs):
        if sel == "rarest_color":
            counts = {}
            for o in objs:
                counts[o["color"]] = counts.get(o["color"], 0) + o["size"]
            if not counts:
                return []
            rare = min(counts, key=lambda c: (counts[c], c))
            return [o for o in objs if o["color"] == rare]
        if sel == "smallest_object":
            return [min(objs, key=lambda o: (o["size"], o["bbox"]))]
        if sel == "corner_sample_color":
            corner = [o for o in objs
                      if o["bbox"][0] < CELL and o["bbox"][1] < CELL]
            if not corner:
                return []
            sample = corner[0]
            return [o for o in objs
                    if o["color"] == sample["color"] and o["id"] != sample["id"]]
        if sel == "largest_object":
            return [max(objs, key=lambda o: o["size"])]
        return []

    def _click_policy(self, grid, frame, avail, _depth=0):
        objs = find_objects(grid)
        if not objs:
            aid = next((a for a in avail if (self.level, a) not in self.blacklist),
                       avail[0])
            return aid, {"game_id": self.game_id}, {"note": "no objects; idle"}
        # skip quarantined selectors (F3: never re-burn budget on them)
        active = [s for s in self.sel_order
                  if self.knowledge.rules.get(s) is None
                  or self.knowledge.rules[s].status != STATUS_QUARANTINED]
        if not active:
            active = list(self.sel_order)
        sel = active[0]
        if not self.queue:
            targets = self._select_targets(sel, objs)
            counts = {}
            for o in objs:
                counts[o["color"]] = counts.get(o["color"], 0) + 1
            targets = sorted(targets,
                             key=lambda o: (counts[o["color"]], o["size"],
                                            o["bbox"]))
            self.queue = targets
            self.queue_ptr = 0
        target = None
        while self.queue_ptr < len(self.queue):
            cand = self.queue[self.queue_ptr]
            cy, cx = cand["centroid"]
            cell = (int(cy) // CELL, int(cx) // CELL)
            if (cand["color"], cell) not in self.clicked_sig:
                target = cand
                break
            self.queue_ptr += 1
        if target is None:
            if _depth >= len(CLICK_SELECTORS):
                ranked, _ = salience_rank(objs)
                o = ranked[0]
                cy, cx = o["centroid"]
                self.pending = {"aid": 6, "kind": "click", "rule": None,
                                "predicted": None, "sig": None,
                                "data": {"x": min(max(int(cx), 0), 63),
                                         "y": min(max(int(cy), 0), 63)}}
                return 6, dict(self.pending["data"]), {
                    "strategy": "fallback", "note": "hypothesis bank exhausted"}
            self._demote(sel, why="all candidates clicked, no progress")
            return self._click_policy(grid, frame, avail, _depth + 1)
        mask = np.zeros_like(grid, dtype=bool)
        for (r, c) in target["pixels"]:
            mask[r, c] = True
        predicted = prim_recolor_region(grid, mask, 0)
        cy, cx = target["centroid"]
        x = min(max(int(round(cx)), 0), 63)
        y = min(max(int(round(cy)), 0), 63)
        sig = (target["color"], (int(cy) // CELL, int(cx) // CELL))
        self.pending = {"aid": 6, "kind": "click", "rule": sel,
                        "predicted": predicted, "sig": sig,
                        "data": {"x": x, "y": y, "game_id": self.game_id}}
        self.queue_ptr += 1
        rec = self.knowledge.rule(sel)
        reasoning = {"strategy": "program_synthesis_v2", "hypothesis": sel,
                     "program": f"click({sel})",
                     "evidence_class": rec.evidence_class,
                     "prediction": "target pixels become background"}
        return 6, dict(self.pending["data"]), reasoning

    # ------------------------------------------------------------- move games
    def _move_policy(self, grid, frame, avail):
        avail = [a for a in avail if a != 0]
        unprobed = [a for a in avail
                    if a not in self.dirs
                    and self.probe_attempts.get(a, 0) < PROBE_ATTEMPT_CAP]
        if unprobed:
            aid = unprobed[0]
            self.pending = {"aid": aid, "kind": "probe", "predicted": None,
                            "data": {"game_id": self.game_id}}
            return aid, {"game_id": self.game_id}, {
                "strategy": "program_synthesis_v2", "phase": "probe controls"}
        objs = find_objects(grid)
        if not objs or self.player_color is None:
            aid = avail[0] if avail else 1
            return aid, {"game_id": self.game_id}, {"note": "no moving object"}
        players = [o for o in objs if o["color"] == self.player_color]
        others = [o for o in objs if o["color"] != self.player_color]
        if not players or not others:
            aid = avail[0] if avail else 1
            return aid, {"game_id": self.game_id}, {"note": "player/goal lost"}
        player = players[0]
        goal = salience_rank(others)[0][0]
        py, px = player["centroid"]
        gy, gx = goal["centroid"]

        def dist_after(a):
            dr, dc = self.dirs.get(a, (0, 0))
            return abs(py + dr * CELL - gy) + abs(px + dc * CELL - gx)

        ordered = sorted(avail, key=dist_after)
        if self.stuck >= 2:      # anti-deadlock jitter (deterministic)
            ordered = ordered[1:] + ordered[:1]
            self.stuck = 0
        aid = ordered[0]
        dr, dc = self.dirs.get(aid, (0, 0))
        mask = np.zeros_like(grid, dtype=bool)
        for (r, c) in player["pixels"]:
            mask[r, c] = True
        predicted = prim_move_region(grid, mask, dr * CELL, dc * CELL)
        self.pending = {"aid": aid, "kind": "move", "predicted": predicted,
                        "data": {"game_id": self.game_id}}
        return aid, {"game_id": self.game_id}, {
            "strategy": "program_synthesis_v2",
            "program": "apply action minimising Manhattan distance to goal",
            "controls": {str(k): v for k, v in self.dirs.items()},
            "player_color": self.player_color, "goal_color": goal["color"]}

    # ------------------------------------------------------------- helpers
    def _demote(self, sel, why):
        if sel in self.sel_order:
            self.sel_order.remove(sel)
            self.sel_order.append(sel)
        self.queue, self.queue_ptr = [], 0
        rec = self.knowledge.rule(sel)
        rec.rotations += 1
        if rec.rotations >= 2 and rec.success == 0:
            rec.status = STATUS_QUARANTINED
            self.ledger.append("RULE_QUARANTINED", rule=sel, cause=why)
            if self.verbose:
                print(f"    [v2] QUARANTINED '{sel}' ({why})")
        else:
            self.ledger.append("RULE_DEMOTED", rule=sel, cause=why)

    def _clear_level_state(self):
        self.queue, self.queue_ptr = [], 0
        self.clicked_sig = set()
        self.blacklist = set()
        self.pending = None
        self.stuck = 0
        self.level_actions = []
        self.level_verified = False
        self.replay = None

    def _grid(self, frame):
        g = merged_view(frame)
        if g is None:
            g = _grid_of(frame)
        return g

    def _available(self, frame):
        try:
            avail = list(getattr(frame, "available_actions", None) or [])
            return [int(a) for a in avail]
        except Exception:
            return []


# ============================================================================
# SECTION 6 — KIT-FACING AGENT (never-hang wrapper + protocol discipline)
# ============================================================================
class ProgramSynthesisV2Agent:
    """MyAgent for the ARC-AGI-3 Kaggle starter kit.

    - choose_action / is_done match the official Agent ABC surface.
    - Every decide path is wrapped: any exception or missing field falls
      back to the cheapest legal action (RESET when required) — it can
      degrade, never hang, never raise.
    - Constructor accepts any kit-style arguments (game_id is sniffed from
      kwargs or the second positional argument when present).
    """

    MAX_ACTIONS = 80
    TIME_BUDGET_S = 1.0

    def __init__(self, *args, **kwargs):
        self.agent_name = (kwargs.get("agent_name")
                           or (args[2] if len(args) > 2 else None)
                           or "ProgramSynthesisV2")
        gid = kwargs.get("game_id")
        if not gid and len(args) > 1 and isinstance(args[1], str):
            gid = args[1]
        self.core = ProgramSynthesisV2Core(
            verbose=bool(kwargs.get("verbose", False)))
        self.action_counter = 0     # bumped by the harness (official main())
        self._steps = 0             # internal mirror, bumped by choose_action
        self.begin_episode(gid or "")

    # -- lifecycle -----------------------------------------------------------
    def begin_episode(self, game_id):
        self.core.new_episode(game_id)

    # -- official ABC surface --------------------------------------------------
    def is_done(self, frames, latest_frame):
        try:
            if _state_name(getattr(latest_frame, "state", None)) == "WIN":
                return True
            return (self.action_counter >= self.MAX_ACTIONS
                    or self._steps >= self.MAX_ACTIONS)
        except Exception:
            return False

    def choose_action(self, frames, latest_frame):
        try:
            t0 = time.perf_counter()
            aid, data, reasoning = self.core.next_action(latest_frame)
            action = self._make_action(aid, data, reasoning)
            self._steps += 1
            if time.perf_counter() - t0 > self.TIME_BUDGET_S:
                self.core.ledger.append("SLOW_DECISION",
                                        seconds=round(time.perf_counter() - t0, 3))
            return action
        except Exception:
            self._steps += 1
            return self._fallback(frames, latest_frame)

    # -- helpers ----------------------------------------------------------------
    @staticmethod
    def _make_action(aid, data, reasoning):
        action = GameAction.from_id(int(aid))
        if data:
            try:
                action.set_data({k: (int(v) if k in ("x", "y") else v)
                                 for k, v in data.items()})
            except Exception:
                pass
        try:
            action.reasoning = reasoning
        except Exception:
            pass
        return action

    def _fallback(self, frames, latest_frame):
        """Never raises. Cheapest legal action; RESET when required."""
        try:
            state = _state_name(getattr(latest_frame, "state", None))
            if state in ("NOT_PLAYED", "GAME_OVER"):
                return self._make_action(0, {"game_id": self.core.game_id},
                                         {"strategy": "fallback_reset"})
            avail = []
            try:
                avail = [int(a) for a in
                         (getattr(latest_frame, "available_actions", None) or [])]
            except Exception:
                avail = []
            if not avail:
                avail = [1, 2, 3, 4, 6]
            aid = avail[0]
            if aid == 6:
                data = {"x": 32, "y": 32, "game_id": self.core.game_id}
            else:
                data = {"game_id": self.core.game_id}
            return self._make_action(aid, data, {"strategy": "safe_fallback"})
        except Exception:
            try:
                return GameAction.RESET
            except Exception:
                return None


MyAgent = ProgramSynthesisV2Agent
